### ISSUE TITLE
Access issue while downloading model files. 

### ISSUE THREAD

**Issue by AshutoshUpadhya** [at16k/at16k#11]
I am trying to download both model files but probably  GCP storage is giving access issue. Can someone pls look into this

(at16k) D:\Research>python -m at16k.download en_16k
Downloading from https://storage.googleapis.com/at16k-ce/models\en_16k.tar.gz
Traceback (most recent call last):
  File "C:\Anaconda3\envs\at16k\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\envs\at16k\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\at16k\lib\site-packages\at16k\download.py", line 83, in <module>
    main()
  File "C:\Anaconda3\envs\at16k\lib\site-packages\at16k\download.py", line 76, in main
    download_model(remote_path, local_path)
  File "C:\Anaconda3\envs\at16k\lib\site-packages\at16k\download.py", line 48, in download_model
    urllib.request.urlretrieve(remote_path, local_path, show_progress)
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 248, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Anaconda3\envs\at16k\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by mohitsshah** [comment]
(at16k) D:\Research>python -m at16k.download en_16k
Downloading from https://storage.googleapis.com/at16k-ce**/models\en_16k.tar.gz**

The problem seems to be in path.join in the following file:
https://github.com/at16k/at16k/blob/61ee1744ac9d0282210c9add2c4f44f1db2ce583/at16k/download.py#L74

It's a Windows specific issue.
Can you contribute towards this and propose a solution?

**Comment by akatasonov** [comment]
@mohitsshah why do you use os.path.join for URLs? URLs are not system paths. Either use urllib or (simpler) just concat strings together, ex: `remote_path = BASE_URL +'/'+ file_name`

**Comment by matthoek** [comment]
I am facing the same issue when downloading any of the 3 models.
Here are the error codes:
C:\Windows\system32>python -m at16k.download all
Downloading from https://storage.googleapis.com/at16k-ce/models\en_8k.tar.gz
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\at16k\download.py", line 83, in <module>
    main()
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\at16k\download.py", line 76, in main
    download_model(remote_path, local_path)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\at16k\download.py", line 48, in download_model
    urllib.request.urlretrieve(remote_path, local_path, show_progress)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by mohitsshah** [comment]
> @mohitsshah why do you use os.path.join for URLs? URLs are not system paths. Either use urllib or (simpler) just concat strings together, ex: `remote_path = BASE_URL +'/'+ file_name`

I agree that's the right way. It'll take a few days for me to post a fix. If anyone can create a PR, I'll merge it.

**Comment by mohitsshah** [comment]
Fixed.
